apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJVMlZ5WjJWNVIzSmxaVzQzT21kb2NGOU5iblowVnpVNWFtOTJNV2c0V2psT1pscE1OMHBqYkZsc1ZHeHRjbG94UVdZd1dqTT0iCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
